### PR TITLE
Use erlef/setup-beam GitHub action

### PR DESCRIPTION
**Pull request by michallepicki**

### CODE REVIEW

**Review by lpil — APPROVED** [review]

**Comment by lpil** [comment]
Looks like it forces an OTP version. We should see if we can remove that requirement.

**Comment by michallepicki** [comment]
Oh snap, I didn't think of that. I will open an issue in `erlef/setup-beam`. If not, maybe the gleam action could still be useful after all.

**Comment by lpil** [comment]
Sounds good. Fingers crossed they'll accept it. I can think of a few use cases

- Type checking Gleam
- Precompiling Gleam
- Gleam JS

**Comment by michallepicki** [comment]
Issue for tracking: https://github.com/erlef/setup-beam/issues/79

**Review by lpil — APPROVED** [review]
Brilliant, thank you

**Pull request merged**
